
"use strict";

const fs = require("fs")

//console.log(fs)
let dir9 = "C:/Work/- AutoScript/IASProject"
let dir = "C:/Work/- AutoScript/"
if(!fs.existsSync(dir)){
    document.getElementById("firstFileWork").innerHTML = "C:/Work/- AutoScript/IASProject - created";
    fs.mkdirSync(dir9)
} else{
    document.getElementById("firstFileWork").innerHTML = "ERROR - file not created";
}


let dir2 = "C:/Work/- AutoScript/IASProject/IAS_CTRL_Common_Files"
let dir3 = "C:/Work/- AutoScript/IASProject/Citect_Project" // unzipped version
let dir4 = "C:/Work/- AutoScript/IASProject/Json_files"
if(!fs.existsSync(dir2)){
    fs.mkdirSync(dir2)
    fs.mkdirSync(dir3)
    fs.mkdirSync(dir4)
    document.getElementById("secondFileWork").innerHTML = "Second path created";
} else {
    document.getElementById("secondFileWork").innerHTML = "ERROR - path not created";
}

let dir5 = "C:/Work/- AutoScript/- Files Autogenerated"
if(!fs.existsSync(dir5)){
    fs.mkdirSync(dir5)
    document.getElementById("thridFileWork").innerHTML = "Second path created";
} else{
    document.getElementById("thridFileWork").innerHTML = "Error - path not created";
}